-- Run this in the Supabase SQL editor before enabling chat persistence.
create table if not exists public.ai_chat_messages (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  patient_id integer,
  question text not null check (char_length(question) between 3 and 4000),
  answer text not null,
  model text not null
);

alter table public.ai_chat_messages enable row level security;

-- The browser never talks to this table directly. The server uses the publishable
-- key and only inserts generated messages; no public read policy is created.
drop policy if exists "allow anonymous ai chat inserts" on public.ai_chat_messages;
create policy "allow anonymous ai chat inserts"
on public.ai_chat_messages
for insert
to anon
with check (char_length(question) between 3 and 4000);
